apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-node-demo
  namespace: harness-node-demo
  labels:
    app: harness-node-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harness-node-demo
  template:
    metadata:
      labels:
        app: harness-node-demo
    spec:
      containers:
        - name: harness-node-demo
          image: <+artifact.image>
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
