pipeline:
  name: CI_Pipeline_2
  identifier: CI_Pipeline_2
  projectIdentifier: Assignment_Vanshika
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: vanshikapahuja
        repoName: Test1
        build: <+input>
  stages:
    - stage:
        name: Build_and_Push
        identifier: Build_and_Push
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build_And_Push_Image
                  identifier: Build_And_Push_Image
                  spec:
                    connectorRef: jfrog_docker_connector
                    repo: trial3wrx99.jfrog.io/docker1-docker-local/my-angular-app
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: test1
